### ISSUE TITLE
Glip breaks when stdin is too large

### ISSUE THREAD

**Issue by gzcharleszhang** [steven-xie/glip#1]
### Input: 
`dgen "hi " 1000 -c`

### Expected result:
"hi " is repeated 1000 times and is stored in the clipbboard.

### Observed:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/26018804/44278838-51819c00-a21d-11e8-854d-dd664a85ef5f.png">

**Comment by steven-xie** [comment]
Resolved as of 91e5677.
